---
Parameters:
  Stage:
    Type: String
    AllowedValues: [dev, beta, production]
  DatabaseName:
    Type: String
  MasterUsername:
    Type: String
  MasterUserPassword:
    Type: String
  MinCapacity:
    Type: Number
  MaxCapacity:
    Type: Number

Resources:
  RDSCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      MasterUsername: !Sub ${MasterUsername}
      MasterUserPassword: !Sub ${MasterUserPassword}
      DatabaseName: !Sub ${DatabaseName}${Stage}
      Engine:  aurora-postgresql
      EngineMode: serverless
      ScalingConfiguration:
        AutoPause: true
        MinCapacity: !Sub ${MinCapacity}
        MaxCapacity: !Sub ${MaxCapacity}
        SecondsUntilAutoPause: 300
