---
Parameters:
  Stage:
    Type: String
    AllowedValues: [dev]
  VpcId:
    Type: String
  AvailabilityZone:
    Type: String
  VolumeTagName:
    Type: String
  VolumeSize:
    Type: Number

Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::Region}-${AWS::StackName}-Role-${Stage}
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement: 
          Effect: Allow
          Principal: 
            Service: ec2.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: !Sub ${AWS::Region}-${AWS::StackName}-Policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: ['ec2:AttachVolume']
                Resource: ['arn:aws:ec2:*:*:instance/*', 'arn:aws:ec2:*:*:volume/*']
              - Effect: Allow
                Action: ['ec2:DescribeVolumes']
                Resource: ['*']
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonAPIGatewayInvokeFullAccess
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess
  InstanceProfile:
    DependsOn: Role
    Type: AWS::IAM::InstanceProfile
    Properties: 
      InstanceProfileName: !Sub ${AWS::Region}-${AWS::StackName}-InstanceProfile-${Stage}
      Roles: 
        - !Ref Role
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${AWS::Region}-${AWS::StackName}-${Stage}
      GroupDescription: Allow remote access to cache
      VpcId: !Sub ${VpcId}
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  Volume:
    Type: AWS::EC2::Volume
    Properties:
      Size: !Sub ${VolumeSize}
      Encrypted: false
      AvailabilityZone: !Sub ${AvailabilityZone}
      Tags:
        - Key: tag-key
          Value: Name
        - Key: tag-value
          Value: !Sub ${VolumeTagName}

Outputs:
  SecurityGroupId:
    Value: !GetAtt SecurityGroup.GroupId
  VolumeId:
    Value: !Ref Volume
  InstanceProfileName:
    Value: !Ref InstanceProfile
