---
Parameters:
  SiteCertificateArn:
    Type: String
  Domain:
    Type: String
  Stage:
    Type: String
  HostedZoneId:
    Type: String

Resources:
  SiteDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub ${Domain}
          - !Sub "*.${Domain}"
        #CacheBehaviors:
        #  - Compress: true
        #    ForwardedValues:
        #      QueryString: false
        #    TargetOriginId: !Sub dev-api-${Stage}-${Domain}-${AWS::Region}
        #    ViewerProtocolPolicy: redirect-to-https
        #    PathPattern: /dev/graphql
        #    AllowedMethods: [GET, HEAD, OPTIONS, PUT, PATCH, POST, DELETE]
        DefaultCacheBehavior:
          Compress: true
          ForwardedValues:
            QueryString: false
          TargetOriginId: !Sub site-${Stage}-${Domain}-${AWS::Region}
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        Origins:
          #- CustomOriginConfig:
          #    HTTPPort: 80
          #    HTTPSPort: 443
          #    OriginProtocolPolicy: https-only
          #  DomainName: !Sub 8y8q0skj0k.execute-api.${AWS::Region}.amazonaws.com
          #  Id: !Sub dev-api-${Stage}-${Domain}-${AWS::Region}
          - CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
            DomainName: !Sub ${Stage}-${AWS::Region}.${Domain}.s3-website-${AWS::Region}.amazonaws.com
            Id: !Sub site-${Stage}-${Domain}-${AWS::Region}
        CustomErrorResponses:
          - ErrorCode: 404
            ResponsePagePath: /404/index.html
            ResponseCode: 404
            ErrorCachingMinTTL: 0
        PriceClass: PriceClass_100
        HttpVersion: http2
        ViewerCertificate:
          AcmCertificateArn: !Sub ${SiteCertificateArn}
          SslSupportMethod: sni-only

  SCWebAppRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Sub ${HostedZoneId}
      Name: !Sub ${Stage}-${AWS::Region}.${Domain}
      Type: A
      AliasTarget:
        DNSName: !GetAtt [SiteDistribution, DomainName]
        HostedZoneId: Z2FDTNDATAQYW2 # magic constant for cloudfront from AWS
