test:
	yarn -s x api test

start:
	yarn -s x api start

request.api:
	yarn -s x api request.api
request.guest:
	yarn -s x api request.guest

logs.auth:
	yarn -s x api logs.auth
logs.api:
	yarn -s x api logs.api
