test:
	yarn -s lam api test $(ARGS)

start:
	yarn -s lam api start

invoke:
	yarn -s lam api invoke.api
invoke.guest:
	yarn -s lam api invoke.api.guest

logs.auth:
	yarn -s vars yarn -s lam api logs.auth
logs.api:
	yarn -s vars yarn -s lam api logs.api
